# Generated by Django 4.2.2 on 2023-06-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
